import Link from 'next/link'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#070d1a] text-white">
      {/* Nav */}
      <header className="border-b border-white/8 px-6 py-4">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <Link href="/" className="text-lg font-black text-white tracking-tight">
            Hustle<span className="text-emerald-400">Guide</span>
          </Link>
          <Link href="/" className="text-slate-400 hover:text-white text-sm transition-colors">← Back</Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-16">
        <div className="mb-12">
          <p className="text-emerald-400 text-sm font-semibold uppercase tracking-widest mb-3">Legal</p>
          <h1 className="text-4xl font-black mb-3">Terms of Service</h1>
          <p className="text-slate-400 text-sm">Last updated: April 2026</p>
        </div>

        <div className="space-y-10 text-slate-300 leading-relaxed">

          <section>
            <h2 className="text-xl font-bold text-white mb-3">1. What HustleGuide is</h2>
            <p className="text-slate-400">HustleGuide is an AI-powered platform that helps individuals discover and follow personalized roadmaps for building income online. By creating an account, you agree to these Terms of Service. If you don't agree, please don't use the service.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">2. Free vs Pro plan</h2>
            <div className="space-y-3 text-slate-400">
              <p><strong className="text-white">Free plan</strong> — includes access to the quiz, path matching, and one active 12-week guide (first 2 weeks only), plus limited AI coach messages.</p>
              <p><strong className="text-white">Pro plan</strong> — includes up to 3 simultaneous guides (all 12 weeks), unlimited AI coach messages, and priority support. Billed monthly at the rate shown on the pricing page.</p>
              <p>Features may change over time. We'll give reasonable notice of any significant changes to plan features.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">3. Payments and refunds</h2>
            <div className="space-y-3 text-slate-400">
              <p>Pro subscriptions are billed monthly. Payments are processed securely by Stripe.</p>
              <p><strong className="text-white">Cancellation</strong> — you can cancel your Pro subscription at any time from the Settings page. Your access continues until the end of the current billing period. No further charges will be made after cancellation.</p>
              <p><strong className="text-white">Refunds</strong> — because guide generation consumes AI processing costs, we do not offer refunds once a guide has been generated during a billing period. If you have a billing dispute, contact us at <a href="mailto:support@hustleguide.app" className="text-emerald-400 hover:underline">support@hustleguide.app</a> and we'll handle it fairly.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">4. AI-generated content</h2>
            <p className="text-slate-400 mb-3">The guides, plans, and advice generated by HustleGuide are produced by an AI (Anthropic's Claude) based on the information you provide. This content is for <strong className="text-white">informational and educational purposes only</strong>.</p>
            <p className="text-slate-400">We do not guarantee any specific income results. Earning money online depends on many factors outside our control including your effort, market conditions, skills, and time invested. Results mentioned in testimonials or examples are not typical and should not be taken as a guarantee of what you will earn.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">5. Acceptable use</h2>
            <p className="text-slate-400 mb-3">You agree not to:</p>
            <ul className="list-disc pl-5 space-y-2 text-slate-400">
              <li>Use the platform for any unlawful purpose.</li>
              <li>Attempt to reverse-engineer, scrape, or copy the platform's content or AI outputs at scale.</li>
              <li>Share your account with others or resell access.</li>
              <li>Abuse the AI coach or generate harmful content.</li>
            </ul>
            <p className="mt-3 text-slate-400">We reserve the right to suspend or terminate accounts that violate these terms, with or without notice.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">6. Limitation of liability</h2>
            <p className="text-slate-400">To the fullest extent permitted by law, HustleGuide and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the service. Our total liability to you for any claim shall not exceed the amount you paid us in the 3 months preceding the claim.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">7. Changes to the service</h2>
            <p className="text-slate-400">We may update, modify, or discontinue parts of the service at any time. We'll give notice of any major changes that affect paid users. Continued use after notice constitutes acceptance of the new terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">8. Governing law</h2>
            <p className="text-slate-400">These terms are governed by the laws of Italy. Any disputes shall be subject to the exclusive jurisdiction of the courts of Italy.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">9. Contact</h2>
            <p className="text-slate-400">
              Questions about these terms? Email us at{' '}
              <a href="mailto:legal@hustleguide.app" className="text-emerald-400 hover:underline">legal@hustleguide.app</a>.
            </p>
          </section>

        </div>
      </main>

      <footer className="border-t border-white/8 px-6 py-8 mt-8">
        <div className="max-w-3xl mx-auto flex flex-wrap gap-4 items-center justify-between text-sm text-slate-500">
          <span>© 2026 HustleGuide</span>
          <div className="flex gap-5">
            <Link href="/privacy" className="hover:text-white transition-colors">Privacy Policy</Link>
            <Link href="/terms" className="text-emerald-400">Terms of Service</Link>
            <a href="mailto:support@hustleguide.app" className="hover:text-white transition-colors">Contact</a>
          </div>
        </div>
      </footer>
    </div>
  )
}
